# Railway Configuration
# Tells Railway how to run your PHP application

[build]
  command = "composer install --no-dev --optimize-autoloader"

[deploy]
  startCommand = "php -S 0.0.0.0:$PORT -t ."

[env]
  PORT = "8080"